### ISSUE TITLE
can't match herbgrind output with video

### ISSUE THREAD

**Issue by dougc333** [uwplse/herbgrind#13]
https://www.youtube.com/watch?v=oYtnXEZC0jk&t=1822s

#include <stdlib.h>
#include <math.h>
#include <stdio.h>

double solve_quadratic(double a, double b, double c){
    //there are 2, a plus and minus; we only take the plus
    return (-b + sqrt(b*b - 4*a*c))/(2*a);
}

int main(int argc, char** argv) {
    double b = 1e-10;
    for (int i =0; i<20; i++){
        b*=10;
        printf("%e\n", solve_quadratic(2,b,c));

    return 0;
}

above saved as main.c
gcc ./main.cpp -O0 -g -lm -o main

/home/dc/herbgrind/valgrind/herbgrind-install/bin/valgrind --tool=herbgrind --no-ranges ./main

main.gh
Result @ main.cpp:21 in main (addr 400730)
47.750810 bits average error
64.000000 bits max error
Aggregated over 20 instances
Influenced by erroneous expression:

    (FPCore (x)
          (/ (- (sqrt (- (* x x) (* 8.000000 3.000000))) x) (+ 2.000000 2.000000)))
   main.cpp:9 in solve_quartic(double, double, double) (addr 400678)
   47.750810 bits average error
   64.000000 bits max error
   32.000000 bits average local error
   64.000000 bits max local error
   Aggregated over 20 instances

![nomatch](https://user-images.githubusercontent.com/124989/38178272-e41d5b38-35c3-11e8-852c-04246ea7d0b6.png)

**Comment by dougc333** [comment]
The FPCore(x) functions are different from the video. Using herbgrind 2.0 from github

**Comment by wilcoxjay** [comment]
Quick clarification: in the code you pasted, you have `solve_quadratic(2,b,c)`, but in the video it's `solve_quadratic(2,b,3)`. Is that just a typo?

**Comment by wilcoxjay** [comment]
In any case, the two influenced-by expressions look equivalent to me: one uses 8.0 where the other uses `(* 4.0 2.0)`.

**Comment by dougc333** [comment]
Typo.. thanks!!

**Comment by wilcoxjay** [comment]
I talked with @pavpanchekha (who is traveling and can't post on github right now) and he said that using a different compiler can cause trivial differences like `(* 4.0 2.0)` vs `8.0`.

I don't see any other differences in the output. Am I missing something or can we close this?

**Comment by HazardousPeach** [comment]
I'm going to close this issue since it seems like @wilcoxjay cleared some stuff up. Feel free to re-open if there's something unresolved!
