### ISSUE TITLE
need help with microbenchmark

### ISSUE THREAD

**Issue by sangeeta0201** [uwplse/herbgrind#36]
Hi,

I have been running John Walker's benchmark which performs a fast Fourier transform of a square matrix, unfortunately, Herbgrind reports "No Marks found".

```
./herbgrind.sh bench/ffbench.c.out
==5847== Herbgrind, a valgrind tool for Herbie
==5847== Copyright (C) 2016-2017, and GNU GPL'd, by Alex Sanchez-Stern
==5847== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==5847== Command: bench/ffbench.c.out
==5847== 
4 passes.  No errors in results.
==5847== 
Didn't find any marks!

```
```
# cat ffbench.c.out.gh 
No marks found!

```

**Comment by pavpanchekha** [comment]
@sangeeta0201 what sort of response are you looking for? Does the benchmark perform any output? Herbgrind considers a floating-point expression relevant if it is connected by control flow to some output. (This is also the definition used by C compilers, which can generally delete dead code.) It is not clear that the benchmark does. If you add some code to, say, output the transformed matrix, Herbgrind would find some marks.

**Comment by HazardousPeach** [comment]
It looks like this issue is due to a benchmark which doesn't produce any output, so I'm going to close this issue. Feel free to correct me if I'm wrong.
