### ISSUE TITLE
benchmark programs do not compile by default

### ISSUE THREAD

**Issue by erich666** [uwplse/herbgrind#41]
It'd be good if `make -C bench all`, as shown on [this page](http://herbgrind.ucsd.edu/using-herbgrind.html), would work without additional work on the user's part. I see that the file mpfr.h is in various deeply-buried subdirectories, but the makefile doesn't know this.

Here's the current error message (Ubuntu Linux), after successfully building herbgrind itself:

ehaines@Ehaines-It:~/Github/herbgrind$ make -C bench all
make: Entering directory '/home/ehaines/Github/herbgrind/bench'
cc -o testprog.c.out testprog.c -g -std=c11 -lm -lmpfr
testprog.c:6:10: fatal error: mpfr.h: No such file or directory
 #include <mpfr.h>
          ^~~~~~~~
compilation terminated.
Makefile:16: recipe for target 'testprog.c.out' failed
make: *** [testprog.c.out] Error 1
make: Leaving directory '/home/ehaines/Github/herbgrind/bench'

**Comment by HazardousPeach** [comment]
Thanks enrih666! I removed that benchmark, which was intended to test a different piece of software, from the repo.
