### ISSUE TITLE
undefined symbol: __muldc3 in Nix environment

### ISSUE THREAD

**Issue by ck3d** [uwplse/herbgrind#42]
I try to packet Herbgrind (latest version) in Nix. The executable _valgrind_ is now built, but it failes to analyse any executable. It raises following error:
```
$ ./valgrind/herbgrind-install/bin/valgrind --tool=herbgrind --output-sexp bench/mini.c.out
==14179== Herbgrind, a valgrind tool for Herbie
==14179== Copyright (C) 2016-2017, and GNU GPL'd, by Alex Sanchez-Stern
==14179== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==14179== Command: bench/mini.c.out
==14179==
bench/mini.c.out: symbol lookup error: /home/test/valgrind/herbgrind-install/lib/valgrind/vgpreload_herbgrind-amd64-linux.so: undefined symbol: __muldc3
==14179==
Didn't find any marks!
```
The symbol __muldc3 was not found. Any idea what is going wrong in my environment?

**Comment by HazardousPeach** [comment]
Hmm, it looks like whatever your provider of libm is, it isn't providing the `__muldc3` symbol, multiplication of complex doubles. I rewrote some of that code to try to be a little more robust, try pulling master and trying again.

**Comment by ck3d** [comment]
Thanks for your fast answer. The master did not change since March. Which master do you mean?

**Comment by HazardousPeach** [comment]
I think the commit I'm referring (b3e4b69) to was written after your issue was submitted, commited at 16:45 on May 15th. Could you give it a try?

**Comment by HazardousPeach** [comment]
Since there hasn't been any movement on this, I'm assuming the commit I sent fixed your issue. Feel free to reopen if you've still got issues!
