### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by hbrunie** [uwplse/herbgrind#48]
Hi,

I had a compiler issue using gcc (GCC) 8.2.0 20180726 (Cray Inc.)

This is an uninitialized variable warning (-->error).
I have added an initialization to NULL in the code just to be able to compile without further problems.

<img width="1914" alt="image" src="https://user-images.githubusercontent.com/5767146/64999515-f3e6d580-d89c-11e9-94b1-a89efe918c5e.png">

**Comment by HazardousPeach** [comment]
Fixed in 7d32042
