### ISSUE TITLE
Adding modf function

### ISSUE THREAD

**Issue by hbrunie** [uwplse/herbgrind#50]
Hi,

fmod and fmodf are both overloaded.
Could modf and modff (or just modf as C++11 standard, [modf](http://www.cplusplus.com/reference/cmath/modf/)) be added too?

Thanks

**Comment by HazardousPeach** [comment]
Hmm, from the documentation for these functions, they seem to produce two outputs, one in the normal return value, and one in an `out` parameter. I think I could add this, but it would be non-trivial as I haven't added any functions with out parameters yet; probably not going to get done right away (pull requests accepted!).

**Comment by HazardousPeach** [comment]
I finally got around to doing this! Should be fixed in 4770550
