### ISSUE TITLE
WARNING: 'automake-1.15' is missing on your system.

### ISSUE THREAD

**Issue by drfortran** [uwplse/herbgrind#60]
Hi !
I can get the older 1.15 version to coexist with 1.16 currently on my machine, but before this, it was causing the following compilation problem:
…
make[1]: Leaving directory '~/herbgrind'
make -C deps/mpfr-64
make[1]: Entering directory '~herbgrind/deps/mpfr-64'
 cd . && /bin/bash ~/herbgrind/deps/mpfr-64/missing automake-1.15 --gnu
~/herbgrind/deps/mpfr-64/missing: line 81: automake-1.15: command not found
WARNING: 'automake-1.15' is missing on your system.

Would you extend the range of possible versions?
Regards,

**Comment by HazardousPeach** [comment]
Unfortunately, that version dependency is within the GNU MPFR library we depend on. It might be possible with some work to change the MPFR and GMP versions, but currently their source archives are bundled with the Herbgrind source. Wish I could be of more help!

**Comment by drfortran** [comment]
Thanks anyway !
