### ISSUE TITLE
Add topic tags in About section

### ISSUE THREAD

**Issue by Beliavsky** [uwplse/herbgrind#66]
I suggest adding the topics `floating-point`, `valgrind`, `debugging`, `numerical-precision` in the About section at https://github.com/uwplse/herbgrind

**Comment by HazardousPeach** [comment]
Unfortunately that would be a bit hard, since while I still have push and admin access to the repository, I am no longer a part of the uwplse github organization, so I'm unable to edit tags on the repo.

**Comment by bilderbuchi** [comment]
> I am no longer a part of the uwplse github organization, so I'm unable to edit tags on the repo.

@ztatlock is, though, and has contributed to this repo in the past, so maybe he would do that?
